apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp
spec:
  selector:
    matchLabels:
      app: mcp
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: mcp
    spec:
      containers:
      - name: mcp
        imagePullPolicy: Always
        image: gcr.io/howardjohn-istio/mcp-load
        args:
        - --services=1
        - --endpoints=100000
        - --delay=10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 5000m
            memory: 5000M
---
apiVersion: v1
kind: Service
metadata:
  name: mcp
  labels:
    app: mcp
spec:
  ports:
  - port: 9901
    name: grpc
  selector:
    app: mcp